const hanoiBank = [
    // Nhóm Cà phê (Cốc thủy tinh)
    { question: "Nâu phố núi (đá) sử dụng lượng sữa đặc là bao nhiêu?", options: ["15g", "20g", "25g", "30g"], answer: "20g" },
    { question: "Lượng đá dùng cho Nâu phố núi (đá) là bao nhiêu?", options: ["80g", "100g", "120g", "150g"], answer: "100g" },
    { question: "Định lượng cafe nâu dùng cho Nâu phố núi (đá) là?", options: ["13g", "15g", "18g", "20g"], answer: "18g" },
    { question: "Nâu phố núi (đá) bấm chiết xuất cốt cafe ở nút mấy, thời gian bao lâu và ra lượng thành phẩm là bao nhiêu?", options: ["Nút 2 (33-36s, 30g)", "Nút 3 (36-40s, 40g)", "Nút 4 (55-65s, 45g)", "Nút 1 (20-25s, 20g)"], answer: "Nút 2 (33-36s, 30g)" },
    { question: "Nâu nóng phố núi sử dụng lượng sữa đặc là bao nhiêu?", options: ["15g", "20g", "25g", "30g"], answer: "20g" },
    { question: "Nâu nóng phố núi bấm chiết xuất cốt cafe ở nút mấy, thời gian bao lâu và ra lượng thành phẩm là bao nhiêu?", options: ["Nút 2 (33-36s, 30g)", "Nút 3 (36-40s, 40g)", "Nút 4 (55-65s, 45g)", "Nút 2 (26-30s, 30g)"], answer: "Nút 4 (55-65s, 45g)" },
    { question: "Đen phố núi (đá) sử dụng loại bột cafe nào và định lượng bao nhiêu?", options: ["18g cafe nâu", "13g cafe ý", "18g cafe đen", "15g cafe đen"], answer: "18g cafe đen" },
    { question: "Đen phố núi (đá) bấm chiết xuất cốt cafe ở nút mấy, thời gian bao lâu và ra lượng thành phẩm là bao nhiêu?", options: ["Nút 2 (33-36s, 30g)", "Nút 3 (36-40s, 40g)", "Nút 4 (55-65s, 45g)", "Nút 3 (40-45s, 45g)"], answer: "Nút 3 (36-40s, 40g)" },
    { question: "Đen phố núi (đá) thêm lượng đường nước là bao nhiêu?", options: ["5ml", "10ml", "15ml", "Không thêm đường"], answer: "5ml" },
    { question: "Đen nóng phố núi chiết xuất ở nút mấy và ra lượng thành phẩm bao nhiêu?", options: ["Nút 3 ra 40g", "Nút 4 ra 45g", "Nút 2 ra 30g", "Nút 4 ra 60g"], answer: "Nút 4 ra 45g" },
    { question: "Đen nóng phố núi được phục vụ kèm với gì?", options: ["1 cốc trà đá", "1 thanh đường que", "5ml đường nước", "20ml sữa đặc"], answer: "1 thanh đường que" },
    { question: "Bạc xỉu đá sử dụng lượng whip và rich là bao nhiêu?", options: ["10ml whip, 10ml rich", "20ml whip, 10ml rich", "10ml whip, 20ml rich", "20ml whip, 20ml rich"], answer: "10ml whip, 10ml rich" },
    { question: "Bạc xỉu đá sử dụng lượng sữa tươi và sữa đặc là bao nhiêu?", options: ["20ml sữa tươi, 20ml sữa đặc", "30ml sữa tươi, 20ml sữa đặc", "30ml sữa tươi, 30ml sữa đặc", "20ml sữa tươi, 30ml sữa đặc"], answer: "30ml sữa tươi, 20ml sữa đặc" },
    { question: "Bạc xỉu đá dùng loại bột cafe nào và ấn nút mấy?", options: ["18g cafe đen, nút 3", "18g cafe nâu, nút 2", "13g cafe ý, nút 2", "18g cafe nâu, nút 4"], answer: "18g cafe nâu, nút 2" },
    { question: "Bạc xỉu nóng sử dụng lượng sữa tươi sục nóng là bao nhiêu?", options: ["150ml", "180ml", "200ml", "220ml"], answer: "180ml" },
    { question: "Bạc xỉu sữa hạt (đá) sử dụng lượng sữa đặc và sữa hạt là bao nhiêu?", options: ["20ml sữa đặc, 50ml sữa hạt", "30ml sữa đặc, 50ml sữa hạt", "30ml sữa đặc, 60ml sữa hạt", "20ml sữa đặc, 60ml sữa hạt"], answer: "30ml sữa đặc, 50ml sữa hạt" },
    { question: "Bạc xỉu sữa hạt sử dụng loại bột cafe nào, ấn nút mấy?", options: ["18g cafe nâu, nút 2", "18g cafe đen, nút 3", "13g cafe ý, nút 2", "15g cafe ý, nút 2"], answer: "13g cafe ý, nút 2" },
    { question: "Bạc xỉu sữa hạt (nóng) sử dụng lượng sữa hạt sục nóng là bao nhiêu?", options: ["150ml", "180ml", "200ml", "220ml"], answer: "180ml" },
    { question: "Cà phê muối (đá) sử dụng lượng sữa đặc và lượng cafe muối là bao nhiêu?", options: ["15ml sữa đặc, 40ml cafe muối", "20ml sữa đặc, 40ml cafe muối", "15ml sữa đặc, 30ml cafe muối", "20ml sữa đặc, 30ml cafe muối"], answer: "15ml sữa đặc, 40ml cafe muối" },
    { question: "Cà phê muối (đá) có lượng đá và kem mặn là bao nhiêu?", options: ["100g đá, 30g kem mặn", "120g đá, 40g kem mặn", "100g đá, 40g kem mặn", "120g đá, 50g kem mặn"], answer: "100g đá, 40g kem mặn" },
    { question: "Decor của Cà phê muối là gì?", options: ["Rắc bột matcha", "Rắc bột cacao", "Rắc bột quế", "Dừa sấy khô"], answer: "Rắc bột cacao" },
    { question: "Americano đá sử dụng lượng nước lọc là bao nhiêu?", options: ["100ml", "120ml", "150ml", "180ml"], answer: "120ml" },
    { question: "Americano (đá và nóng) sử dụng loại bột cafe nào, ấn nút mấy?", options: ["18g cafe đen, nút 3", "18g cafe nâu, nút 2", "13g cafe ý, nút 2", "18g cafe ý, nút 2"], answer: "18g cafe ý, nút 2" },
    { question: "Americano nóng sử dụng lượng nước nóng là bao nhiêu?", options: ["100ml", "120ml", "150ml", "180ml"], answer: "150ml" },
    { question: "Nâu sài gòn (chỉ làm đá) sử dụng lượng sữa đặc, rich, sữa tươi là bao nhiêu?", options: ["30ml sữa đặc, 20ml rich, 10ml sữa tươi", "20ml sữa đặc, 10ml rich, 20ml sữa tươi", "30ml sữa đặc, 10ml rich, 20ml sữa tươi", "20ml sữa đặc, 20ml rich, 10ml sữa tươi"], answer: "30ml sữa đặc, 20ml rich, 10ml sữa tươi" },
    { question: "Nâu sài gòn dùng cốt cafe loại nào?", options: ["18g cafe đen", "18g cafe nâu", "13g cafe ý", "15g cafe nâu"], answer: "18g cafe nâu" },
    { question: "Đen sài gòn sử dụng lượng đường nước là bao nhiêu?", options: ["5ml", "10ml", "15ml", "20ml"], answer: "10ml" },
    { question: "Đen sài gòn cần lắc bao nhiêu lần trước khi đổ ra cốc?", options: ["Không cần lắc", "Lắc 2 lần", "Lắc 3 lần", "Lắc 5 lần"], answer: "Lắc 3 lần" },
    { question: "Capucino nóng sử dụng lượng cafe ý và sữa sục nóng như thế nào?", options: ["13g cafe ý, 200ml sữa sục nóng dùng thìa đổ hình", "18g cafe ý, 180ml sữa sục nóng đổ hình", "13g cafe ý, 200ml sữa sục nóng đổ trực tiếp", "15g cafe ý, 150ml sữa sục nóng dùng thìa đổ hình"], answer: "13g cafe ý, 200ml sữa sục nóng dùng thìa đổ hình" },
    { question: "Latte nóng sử dụng lượng cafe ý và sữa sục nóng như thế nào?", options: ["13g cafe ý, 200ml sữa sục nóng đổ trực tiếp", "13g cafe ý, 200ml sữa sục nóng dùng thìa đổ hình", "18g cafe ý, 180ml sữa sục nóng đổ hình", "15g cafe ý, 200ml sữa sục nóng đổ trực tiếp"], answer: "13g cafe ý, 200ml sữa sục nóng đổ hình" },

    // Nhóm Cold Brew (chỉ cốc thủy tinh, viền muối cốc)
    { question: "Tất cả các món Cold Brew (trừ chai đóng sẵn) đều BẮT BUỘC phải làm thao tác gì với miệng cốc?", options: ["Viền đường", "Viền muối", "Hơ lửa", "Xịt viền chanh"], answer: "Viền muối" },
    { question: "Cold brew dâu tằm sử dụng lượng cold brew và dâu tằm là bao nhiêu?", options: ["100ml cold brew, 1 tép dâu tằm", "120ml cold brew, 2 tép dâu tằm", "100ml cold brew, 2 tép dâu tằm", "150ml cold brew, 1 tép dâu tằm"], answer: "100ml cold brew, 1 tép dâu tằm" },
    { question: "Cold brew dâu tằm sử dụng lượng đường nước và đường hoa quả là bao nhiêu?", options: ["10ml đường nước, 5ml đường hoa quả", "20ml đường nước, 5ml đường hoa quả", "15ml đường nước, 10ml đường hoa quả", "20ml đường nước, 10ml đường hoa quả"], answer: "20ml đường nước, 5ml đường hoa quả" },
    { question: "Thao tác pha chế của Cold brew dâu tằm là gì?", options: ["Lắc đều (shake)", "Chỉ quậy", "Xay với đá", "Sục hơi"], answer: "Chỉ quậy" },
    { question: "Cold brew me đác sử dụng lượng mứt me đác là bao nhiêu?", options: ["20g", "30g", "40g", "50g"], answer: "30g" },
    { question: "Cold brew me đác sử dụng lượng đường nước và đường hoa quả là bao nhiêu?", options: ["10ml đường, 5ml đường hoa quả", "20ml đường, 5ml đường hoa quả", "15ml đường, 5ml đường hoa quả", "10ml đường, 10ml đường hoa quả"], answer: "10ml đường, 5ml đường hoa quả" },
    { question: "Cold brew sấu hà nội sử dụng lượng cốt sấu và quả sấu là bao nhiêu?", options: ["20ml cốt sấu, 2 quả sấu", "30ml cốt sấu, 2 quả sấu", "20ml cốt sấu, 3 quả sấu", "30ml cốt sấu, 3 quả sấu"], answer: "20ml cốt sấu, 2 quả sấu" },
    { question: "Cold brew cam sử dụng lượng đường nước và đường hoa quả là bao nhiêu?", options: ["20ml đường, 5ml đường hoa quả", "10ml đường, 5ml đường hoa quả", "15ml đường, 10ml đường hoa quả", "25ml đường, 5ml đường hoa quả"], answer: "20ml đường, 5ml đường hoa quả" },
    { question: "Cold brew cam sử dụng bao nhiêu ml cam ép và xử lý thế nào?", options: ["100ml cam, để nguyên tép", "100ml cam, lọc qua dây lọc", "120ml cam, lọc qua dây lọc", "80ml cam, để nguyên tép"], answer: "100ml cam, lọc qua dây lọc" },
    { question: "Thao tác rót của Cold brew cam là gì?", options: ["Trộn đều rồi rót", "Rót phân tầng", "Lắc chung với đá rồi rót", "Rót cold brew xuống dưới cùng"], answer: "Rót phân tầng" },
    { question: "Cold brew mơ sử dụng lượng mứt mơ là bao nhiêu?", options: ["20g (2 quả)", "30g (3 quả và nước mơ)", "40g (4 quả)", "30g (chỉ lấy nước)"], answer: "30g mứt mơ (gồm 3 quả và nước mơ)" },
    { question: "Cold brew mơ sử dụng lượng đường nước và đường hoa quả là bao nhiêu?", options: ["10ml đường, 5ml đường hoa quả", "15ml đường, 5ml đường hoa quả", "20ml đường, 5ml đường hoa quả", "15ml đường, 10ml đường hoa quả"], answer: "15ml đường (nước), 5ml đường hoa quả" },
    { question: "Cold brew chanh vàng sử dụng lượng mứt chanh vàng là bao nhiêu?", options: ["5ml", "10ml", "15ml", "20ml"], answer: "10ml" },
    { question: "Cold brew nguyên bản sử dụng lượng cold brew và đá là bao nhiêu?", options: ["100ml cold brew, 100g đá", "120ml cold brew, 120g đá", "150ml cold brew, 100g đá", "100ml cold brew, 120g đá"], answer: "100ml cold brew, 100g đá (đầy cốc)" },
    { question: "Chai Cold brew bán sẵn (chai thủy tinh cấp sẵn) chứa bao nhiêu ml?", options: ["200ml", "250ml", "300ml", "330ml"], answer: "250ml" },

    // Nhóm Sen Huế
    { question: "Sen huế size M sử dụng lượng nước dừa và nước cốt sen là bao nhiêu?", options: ["150ml nước dừa, 40ml nước cốt sen", "200ml nước dừa, 60ml nước cốt sen", "150ml nước dừa, 50ml nước cốt sen", "120ml nước dừa, 40ml nước cốt sen"], answer: "150ml nước dừa, 40ml nước cốt sen" },
    { question: "Topping của Sen huế size M gồm những gì?", options: ["50g hạt sen, 5g dừa sợi, cánh sen, 4 quả nhãn", "50g hạt sen, 10g dừa sợi, cánh sen, 5 quả nhãn", "40g hạt sen, 5g dừa sợi, 4 quả nhãn", "50g hạt sen, thạch dừa, cánh sen, 4 quả nhãn"], answer: "50g hạt sen, 5g dừa sợi, cánh sen, 4 quả nhãn" },
    { question: "Sen huế size L sử dụng lượng nước dừa và nước cốt sen là bao nhiêu?", options: ["150ml nước dừa, 40ml nước cốt sen", "200ml nước dừa, 60ml nước cốt sen", "250ml nước dừa, 70ml nước cốt sen", "200ml nước dừa, 50ml nước cốt sen"], answer: "200ml nước dừa, 60ml nước cốt sen" },
    { question: "Topping của Sen huế size L gồm những gì?", options: ["50g hạt sen, 5g dừa sợi, cánh sen, 5 quả nhãn", "60g hạt sen, 5g dừa sợi, cánh sen, 4 quả nhãn", "50g hạt sen, 10g dừa sợi, cánh sen, 6 quả nhãn", "50g hạt sen, 5g dừa sợi, cánh sen, 4 quả nhãn"], answer: "50g hạt sen, 5g dừa sợi, cánh sen, 5 quả nhãn" },

    // Nhóm Bơ
    { question: "Hỗn hợp để dưới đáy cốc của món Bơ dừa non gồm những gì?", options: ["35ml cốt dừa, 15ml đường, 10ml whiping, đá vụn 20g", "30ml cốt dừa, 10ml đường, 15ml whiping, đá vụn 20g", "40ml cốt dừa, 15ml đường, 10ml whiping, đá vụn 30g", "35ml cốt dừa, 20ml đường, 10ml whiping, đá vụn 20g"], answer: "35ml cốt dừa, 15ml đường, 10ml whiping, đá vụn 20g" },
    { question: "Nguyên liệu cho vào cối xay của Bơ dừa non là gì?", options: ["1 túi bơ, 50ml nước lọc, 30ml sữa tươi, 20g sữa đặc, 10ml siro lá nếp", "1 túi bơ, 30ml nước lọc, 50ml sữa tươi, 20g sữa đặc, 10ml siro lá nếp", "1 túi bơ, 50ml nước lọc, 30ml sữa tươi, 30g sữa đặc, 5ml siro lá nếp", "1 túi bơ, 50ml nước lọc, 40ml sữa tươi, 20g sữa đặc, 10ml siro lá nếp"], answer: "Bơ 1 túi, 50ml nước lọc, 30ml sữa tươi, 20g sữa đặc, 10ml siro lá nếp" },
    { question: "Decor của món Bơ dừa non là gì?", options: ["Vụn điều 3g", "Dừa khô 5g", "Hạt dẻ cười", "Dừa tươi nạo sợi"], answer: "Vụn điều 3g" },
    { question: "Nguyên liệu cho vào cối xay của món Kem bơ là gì?", options: ["1 túi bơ, 30g đá viên, 50ml nước lọc, 30ml sữa tươi, 20ml sữa đặc, 10ml siro lá nếp", "1 túi bơ, 50g đá viên, 50ml nước lọc, 30ml sữa tươi, 20ml sữa đặc, 10ml siro lá nếp", "1 túi bơ, 30g đá viên, 30ml nước lọc, 50ml sữa tươi, 20ml sữa đặc, 10ml siro lá nếp", "1 túi bơ, 30g đá viên, 50ml nước lọc, 30ml sữa tươi, 30ml sữa đặc, 10ml siro lá nếp"], answer: "1 túi bơ, 30g đá viên, 50ml nước lọc, 30ml sữa tươi, 20ml sữa đặc, 10ml siro lá nếp" },
    { question: "Topping và decor của món Kem bơ là gì?", options: ["80g kem dừa (1 viên), dừa khô 5g", "100g kem dừa (2 viên), dừa khô 5g", "50g kem dừa (1 viên), vụn điều 3g", "80g kem dừa (1 viên), vụn điều 5g"], answer: "80g kem dừa (1 viên), dừa khô 5g" },
    { question: "Sinh tố bơ có nguyên liệu xay giống Kem bơ nhưng được thêm thành phần gì vào thẳng cối xay?", options: ["35ml cốt dừa, 15ml đường", "30ml cốt dừa, 10ml đường", "20ml whipping", "40ml sữa đặc"], answer: "35ml cốt dừa, 15ml đường" },
    { question: "Đá viên dùng trong cối xay của Sinh tố bơ là bao nhiêu gram?", options: ["20g", "30g", "40g", "50g"], answer: "30g" },
    { question: "Decor của món Sinh tố bơ là gì?", options: ["Vụn điều 3g", "Dừa khô 5g", "Lá bạc hà", "Dừa sấy khô"], answer: "Vụn điều 3g" },

    // Nhóm Trà Trái Cây
    { question: "Lục trà xoài sử dụng lượng nền lục trà và nước lọc là bao nhiêu?", options: ["100ml lục trà, 50ml nước lọc", "120ml lục trà, 30ml nước lọc", "150ml lục trà, không nước lọc", "80ml lục trà, 50ml nước lọc"], answer: "100ml lục trà, 50ml nước lọc" },
    { question: "Lục trà xoài sử dụng lượng mứt xoài là bao nhiêu?", options: ["20ml", "30ml", "40ml", "50ml"], answer: "30ml" },
    { question: "Lục trà xoài sử dụng lượng đường nước và đường hoa quả là bao nhiêu?", options: ["10ml đường, 5ml đường hoa quả", "15ml đường, 5ml đường hoa quả", "10ml đường, 10ml đường hoa quả", "20ml đường, 5ml đường hoa quả"], answer: "10ml đường, 5ml đường hoa quả" },
    { question: "Trà đào sấu sử dụng lượng nước cốt sấu và mứt đào là bao nhiêu?", options: ["30ml cốt sấu, 20g mứt đào", "20ml cốt sấu, 30g mứt đào", "30ml cốt sấu, 30g mứt đào", "40ml cốt sấu, 20g mứt đào"], answer: "30ml cốt sấu, 20g mứt đào" },
    { question: "Trà đào sấu sử dụng bao nhiêu quả sấu?", options: ["1 quả", "2 quả", "3 quả", "4 quả"], answer: "2 quả sấu" },
    { question: "Trong Trà đào sấu, Atiso được xử lý như thế nào?", options: ["Lắc chung với trà", "Rót 30ml atiso lên trên cùng", "Trộn chung dưới đáy cốc", "Không sử dụng Atiso"], answer: "30ml atiso rót lên trên" },
    { question: "Lục trà me đác sử dụng lượng mứt me đác là bao nhiêu?", options: ["20ml", "30ml", "40ml", "50ml"], answer: "30ml" },
    { question: "Lục trà me đác sử dụng loại thạch gì và lượng bao nhiêu?", options: ["70g thạch hồng đào", "50g thạch dừa", "70g thạch atiso", "70g thạch trà"], answer: "70g thạch hồng đào" },
    { question: "Mơ trà sử dụng lượng mơ là bao nhiêu?", options: ["20g (2 quả)", "30g (3 quả)", "40g (4 quả)", "50g (5 quả)"], answer: "30g (3 quả)" },
    { question: "Mơ trà sử dụng loại thạch gì?", options: ["70g thạch atiso", "70g thạch hồng đào", "70g thạch trà", "50g thạch dừa"], answer: "70g thạch hồng đào" },
    { question: "Mơ trà sử dụng cốt atiso như thế nào?", options: ["Khuấy đều cùng trà", "30ml cốt atiso rót lên trên", "Không sử dụng Atiso", "20ml cốt atiso rót dưới đáy"], answer: "30ml cốt atiso (rót lên trên)" },
    { question: "Trà đào cam sả sử dụng lượng hồng trà và nước sôi là bao nhiêu?", options: ["20ml hồng trà, 70ml nước sôi", "30ml hồng trà, 70ml nước sôi", "20ml hồng trà, 100ml nước sôi", "50ml hồng trà, 50ml nước sôi"], answer: "20ml hồng trà, 70ml nước sôi" },
    { question: "Trà đào cam sả sử dụng lượng cốt sả và mứt đào là bao nhiêu?", options: ["30ml cốt sả, 25g mứt đào", "20ml cốt sả, 30g mứt đào", "30ml cốt sả, 20g mứt đào", "40ml cốt sả, 25g mứt đào"], answer: "30ml cốt sả, 25g mứt đào" },
    { question: "Trà đào cam sả sử dụng lượng siro cam đỏ là bao nhiêu?", options: ["3ml", "5ml", "10ml", "15ml"], answer: "3ml" },
    { question: "Topping trang trí của Trà đào cam sả gồm những gì?", options: ["50g đào (2 miếng), 1 lát cam vàng (30g)", "30g đào (1 miếng), 2 lát cam vàng", "Thạch hồng đào, 1 lát cam vàng", "Đào miếng và lá bạc hà"], answer: "50g đào (2 miếng), 1 lát cam vàng (30g)" },
    { question: "Xoài lài chanh leo sử dụng lượng mứt xoài và chanh leo tươi là bao nhiêu?", options: ["20g mứt xoài, 1 túi chanh leo", "30g mứt xoài, 1 túi chanh leo", "20g mứt xoài, nửa túi chanh leo", "30g mứt xoài, nửa túi chanh leo"], answer: "20g mứt xoài, 1 túi chanh leo" },
    { question: "Xoài lài chanh leo sử dụng loại thạch gì?", options: ["70g thạch hồng đào", "70g thạch trà", "50g thạch dừa", "50g pudding xoài"], answer: "70 thạch trà" },

    // Nhóm Trà Sữa Size L
    { question: "Lục trà sữa (size L) sử dụng lượng lục trà là bao nhiêu?", options: ["120ml", "150ml", "180ml", "200ml"], answer: "150ml" },
    { question: "Lục trà sữa (size L) sử dụng lượng sữa nước, sữa đặc, sữa tươi là bao nhiêu?", options: ["30ml sữa nước, 30ml sữa đặc, 50ml sữa tươi", "20ml sữa nước, 30ml sữa đặc, 50ml sữa tươi", "30ml sữa nước, 20ml sữa đặc, 50ml sữa tươi", "30ml sữa nước, 30ml sữa đặc, 30ml sữa tươi"], answer: "30ml sữa nước, 30ml sữa đặc, 50ml sữa tươi" },
    { question: "Lục xoài sữa (size L) sử dụng lượng mứt xoài là bao nhiêu?", options: ["20g", "30g", "40g", "50g"], answer: "30g" },
    { question: "Topping của Lục xoài sữa (size L) gồm những gì?", options: ["Puding xoài 50g, 50g thạch dừa", "Puding xoài 70g", "Thạch hồng đào 50g, thạch dừa 50g", "Puding xoài 50g, thạch atiso 50g"], answer: "Puding xoài 50g, 50g thạch dừa" },
    { question: "Trà sữa đào hồng (size L) sử dụng lượng hồng trà là bao nhiêu?", options: ["70ml", "100ml", "120ml", "150ml"], answer: "70ml" },
    { question: "Trà sữa đào hồng (size L) sử dụng lượng mứt đào hồng là bao nhiêu?", options: ["15g", "20g", "25g", "30g"], answer: "20g" },
    { question: "Nếp hạt dẻ (size L) sử dụng nền trà gì và lượng bao nhiêu?", options: ["150ml lục trà", "150ml hồng trà", "150ml trà gạo", "120ml lục trà"], answer: "150ml lục trà" },
    { question: "Nếp hạt dẻ (size L) sử dụng lượng lá nếp là bao nhiêu?", options: ["10ml", "15ml", "20ml", "25ml"], answer: "15ml" },
    { question: "Nếp hạt dẻ (size L) sử dụng lượng kem hạt dẻ là bao nhiêu?", options: ["30g", "40g", "50g", "60g"], answer: "40g" },
    { question: "Hồng trà hạt dẻ (size L) sử dụng lượng hồng trà là bao nhiêu?", options: ["70ml", "100ml", "120ml", "150ml"], answer: "70ml" },
    { question: "Topping của Hồng trà hạt dẻ (size L) gồm những gì?", options: ["40g kem hạt dẻ, 50g thạch dừa", "50g kem hạt dẻ, 50g thạch dừa", "40g kem hạt dẻ, thạch hồng đào", "Chỉ có 40g kem hạt dẻ"], answer: "40g kem hạt dẻ, 50g thạch dừa" },
    { question: "Trà sữa gạo (size L) sử dụng lượng cốt trà sữa gạo chuẩn bị sẵn là bao nhiêu?", options: ["200ml", "250ml", "300ml", "350ml"], answer: "250ml" },
    { question: "Trà sữa gạo (size L) sử dụng loại topping nào?", options: ["50g thạch dừa", "50g thạch hồng đào", "70g thạch phô mai", "50g pudding"], answer: "50g thạch dừa" },
    { question: "Trà sữa gạo hạt dẻ (size L) sử dụng lượng cốt trà sữa gạo chuẩn bị sẵn là bao nhiêu?", options: ["150ml", "200ml", "250ml", "300ml"], answer: "200ml" },
    { question: "Topping của Trà sữa gạo hạt dẻ (size L) gồm những gì?", options: ["50g thạch dừa, 40g kem hạt dẻ", "50g thạch dừa, 30g kem hạt dẻ", "70g thạch phô mai, 40g kem hạt dẻ", "Chỉ 40g kem hạt dẻ"], answer: "50g thạch dừa, 40g kem hạt dẻ" },
    { question: "Trà sữa gạo pudding phomai (size L) sử dụng lượng cốt trà sữa gạo chuẩn bị sẵn là bao nhiêu?", options: ["150ml", "200ml", "250ml", "300ml"], answer: "200ml" },
    { question: "Lượng thạch phô mai dùng cho Trà sữa gạo pudding phomai là bao nhiêu?", options: ["50g", "60g", "70g", "80g"], answer: "70g" },

    // Nhóm Nước Trái Cây
    { question: "Nước dâu tằm sử dụng bao nhiêu tép dâu tằm?", options: ["1 tép (30ml)", "2 tép (60ml)", "3 tép (90ml)", "4 tép (120ml)"], answer: "2 tép dâu tằm (60ml)" },
    { question: "Nước dâu tằm được mix thêm mứt gì?", options: ["20g mứt đào", "20g mứt xoài", "15g mứt dâu tây", "Không mix thêm mứt"], answer: "20g mứt đào" },
    { question: "Nước dưa hấu cần dùng bao nhiêu gram dưa hấu quả để ép?", options: ["300g", "400g", "500g", "600g"], answer: "400g" },
    { question: "Nước dưa hấu sử dụng lượng đường là bao nhiêu?", options: ["5ml", "10ml", "15ml", "20ml"], answer: "10ml" },
    { question: "Nước cam tươi cần dùng bao nhiêu gram cam quả để vắt?", options: ["300g", "400g", "500g", "600g"], answer: "500g" },
    { question: "Nước cam tươi sử dụng lượng đường là bao nhiêu?", options: ["10ml", "15ml", "20ml", "25ml"], answer: "15ml" },
    { question: "Chanh leo xoài sử dụng lượng chanh leo và mứt xoài là bao nhiêu?", options: ["1 túi chanh leo (30ml), 30ml mứt xoài", "1 túi chanh leo, 20ml mứt xoài", "2 túi chanh leo, 30ml mứt xoài", "1 túi chanh leo, 40ml mứt xoài"], answer: "1 túi chanh leo (30ml), 30ml mứt xoài" },
    { question: "Chanh vàng violet (đá) sử dụng lượng chanh là bao nhiêu?", options: ["1 túi chanh (30g)", "2 túi chanh", "3 lát chanh vàng tươi", "20ml nước cốt chanh"], answer: "1 túi chanh (30g)" },
    { question: "Chanh vàng violet (đá) rót thành phần gì lên trên cùng?", options: ["30ml cốt atiso", "30ml cốt hoa đậu biếc", "20ml siro violet", "10ml siro hoa hồng"], answer: "30ml cốt hoa đậu biếc" },
    { question: "Chanh vàng (nóng) sử dụng lượng nước sôi là bao nhiêu?", options: ["100ml", "120ml", "150ml", "200ml"], answer: "150ml" },
    { question: "Chanh vàng (nóng) dùng kỹ thuật pha chế nào?", options: ["Khuấy đều", "Shake (lắc) lên", "Sục hơi (steam)", "Đổ nước sôi trực tiếp vào cốc"], answer: "Shake lên" },

    // Nhóm Đồ Nóng & Khác
    { question: "Sữa gừng táo đỏ sử dụng lượng sữa tươi là bao nhiêu?", options: ["150ml", "180ml", "200ml", "250ml"], answer: "200ml" },
    { question: "Sữa gừng táo đỏ sử dụng loại sốt nào và định lượng bao nhiêu?", options: ["10ml sốt nướng, 10ml sốt táo đỏ", "20ml sốt táo đỏ", "15ml sốt nướng, 5ml sốt táo đỏ", "10ml sốt caramel, 10ml sốt táo đỏ"], answer: "10ml sốt nướng, 10ml sốt táo đỏ" },
    { question: "Decor của Sữa gừng táo đỏ gồm những gì?", options: ["2g hoa hồng, 2 lát gừng, 2 quả táo đỏ", "1g hoa hồng, 1 lát gừng, 3 quả táo đỏ", "Bột quế, 2 lát gừng", "3 lát gừng, 2 quả táo đỏ"], answer: "2g hoa hồng, 2 lát gừng, 2 quả táo đỏ" },
    { question: "Lài sữa hạt dẻ nóng sử dụng nền trà gì và lượng bao nhiêu?", options: ["150ml lục trà", "150ml hồng trà", "150ml sữa tươi", "120ml lục trà"], answer: "150ml lục trà" },
    { question: "Lài sữa hạt dẻ nóng sử dụng lượng bột hạt dẻ là bao nhiêu?", options: ["10g", "15g", "20g", "25g"], answer: "20g bột hạt dẻ" },
    { question: "Matcha sữa hạt sử dụng lượng sữa hạt là bao nhiêu?", options: ["30ml", "40ml", "50ml", "60ml"], answer: "50ml" },
    { question: "Matcha latte (đá) sử dụng lượng bột matcha là bao nhiêu?", options: ["2g", "1 túi matcha (3g)", "5g", "10g"], answer: "1 túi matcha (3g)" },
    { question: "Matcha latte (nóng) sử dụng lượng sữa tươi sục nóng là bao nhiêu?", options: ["150ml", "180ml", "200ml", "220ml"], answer: "180ml sữa tươi sục nóng vẽ hình" },
    { question: "Matcha kem muối sử dụng lượng sữa hạt và kem muối là bao nhiêu?", options: ["50ml sữa hạt, 40g kem muối", "30ml sữa hạt, 50g kem muối", "30ml sữa hạt, 40g kem muối", "50ml sữa hạt, 50g kem muối"], answer: "30ml sữa hạt, 50g kem muối" },
    { question: "Coco matcha sử dụng loại topping gì và lượng bao nhiêu?", options: ["100g kem dừa + dừa khô", "50g kem dừa + vụn điều", "80g kem dừa + dừa khô", "120g kem dừa + dừa sấy"], answer: "100g kem dừa + dừa khô" },
    { question: "Kem dừa (phục vụ ra cốc riêng) có khối lượng là bao nhiêu?", options: ["150g", "200g", "250g", "300g"], answer: "250g kem dừa" },
    { question: "Sữa chua cafe sử dụng lượng cà phê muối rưới lên trên là bao nhiêu?", options: ["10ml", "20ml", "30ml", "40ml"], answer: "20ml cà phê muối" },
    { question: "Sữa chua dẻo hoa quả sử dụng bao nhiêu gram sữa chua dẻo?", options: ["50g", "80g", "100g", "120g"], answer: "100g" },
    { question: "Cacao (đá) sử dụng lượng sữa đặc và nước sôi như thế nào?", options: ["30g sữa đặc đánh tan với 50ml nước sôi", "40g sữa đặc đánh tan với 50ml nước sôi", "40g sữa đặc đánh tan với 30ml nước sôi", "50g sữa đặc đánh tan với 50ml nước sôi"], answer: "40g sữa đặc đánh tan với 50ml nước sôi" },
    { question: "Cacao (nóng) sử dụng lượng bột cacao là bao nhiêu?", options: ["5g", "10g", "15g", "20g"], answer: "10g cacao" },
    { question: "Cacao (nóng) sử dụng lượng sữa tươi sục nóng là bao nhiêu?", options: ["150ml", "180ml", "200ml", "220ml"], answer: "180ml sữa tươi sục nóng vẽ hình" },

    // Nhóm Chuẩn bị nguyên liệu (Prep)
    { question: "Công thức làm Kem Mặn chuẩn sử dụng tỷ lệ Whipping Anchor và Base là bao nhiêu?", options: ["300g Whip + 500g Base", "400g Whip + 600g Base", "500g Whip + 500g Base", "400g Whip + 500g Base"], answer: "400g Whipping anchor + 600g base" },
    { question: "Làm Kem Mặn sử dụng lượng đường nước và muối hồng là bao nhiêu?", options: ["50ml đường nước, 5g muối", "60ml đường nước, 7g muối", "60ml đường nước, 10g muối", "80ml đường nước, 7g muối"], answer: "60ml đường nước, 7g muối" },
    { question: "Công thức làm Kem Hạt Dẻ Cười sử dụng tỷ lệ sữa tươi, base, whipping là bao nhiêu?", options: ["100ml sữa tươi, 100ml base, 100ml whipping", "150ml sữa tươi, 100ml base, 100ml whipping", "100ml sữa tươi, 150ml base, 100ml whipping", "100ml sữa tươi, 100ml base, 150ml whipping"], answer: "100ml sữa tươi, 100ml base, 100ml whipping" },
    { question: "Công thức làm Kem Hạt Dẻ Cười sử dụng lượng bột hạt dẻ cười là bao nhiêu?", options: ["50g", "80g", "100g", "150g"], answer: "100g" },
    { question: "Để làm Thạch Hồng Đào, 1 túi Atiso cần ủ với bao nhiêu lít nước sôi?", options: ["1.5 lít (1500ml)", "2 lít (2000ml)", "2.5 lít (2500ml)", "3 lít (3000ml)"], answer: "2 lít (2000ml)" },
    { question: "Thời gian ủ Atiso làm Thạch Hồng Đào là bao lâu?", options: ["5 phút", "10 phút", "12 phút", "15 phút"], answer: "10 phút" },
    { question: "Quy trình ủ Trà Sữa Gạo sử dụng 1 túi trà gạo ủ với bao nhiêu ml nước sôi?", options: ["2000ml", "2500ml", "3000ml", "3500ml"], answer: "2500ml" },
    { question: "Thời gian ủ Trà Sữa Gạo là bao lâu và thao tác đặc biệt trước khi vớt bã là gì?", options: ["Ủ 15 phút, vớt nhẹ", "Ủ 18 phút, dầm mạnh 10 lần rồi vớt", "Ủ 12 phút, không tác động", "Ủ 20 phút, vớt nhanh"], answer: "Ủ 18 phút, dầm mạnh 10 lần rồi vớt bã trà" },
    { question: "Trà sữa gạo sau khi pha bột sữa, sốt nướng, đường và đá sẽ có tổng lượng thành phẩm là bao nhiêu?", options: ["3000ml", "3500ml", "4000ml", "4500ml"], answer: "4000ml" },
    { question: "Quy trình ủ Lục Trà chuẩn là gì?", options: ["1 tép lục trà + 2000ml nước sôi, ủ 12p vớt nhẹ (không tác động)", "1 tép lục trà + 1500ml nước sôi, ủ 10p", "1 tép lục trà + 2500ml nước sôi, ủ 15p dầm mạnh", "1 tép lục trà + 2000ml nước sôi, ủ 12p dầm mạnh"], answer: "1 tép lục trà + 2000ml nước sôi, ủ 12p vớt nhẹ (không tác động)" },
    { question: "Cách làm cốt dừa chuẩn tỷ lệ bao nhiêu?", options: ["1 hộp cốt dừa 1000ml + 500ml đường nước", "1 hộp cốt dừa 1000ml + 300ml đường nước", "500ml cốt dừa + 500ml đường nước", "1000ml cốt dừa + 1000ml sữa tươi"], answer: "1 hộp cốt dừa 1000ml + 500ml đường nước" },
    { question: "Cách làm cốt sả chuẩn tỷ lệ và thời gian xay là bao nhiêu?", options: ["100g sả + 500ml nước sôi xay 10s", "200g sả + 600ml nước sôi xay 10s", "200g sả + 500ml nước sôi xay 20s", "300g sả + 600ml nước sôi xay 15s"], answer: "200g sả + 600ml nước sôi xay 10s rồi lọc" }
];
