const hanoiBank = [
    // Mục cà phê (cốc thủy tinh)
    { question: "Nâu phố núi (đá) sử dụng lượng sữa đặc và đá là bao nhiêu?", options: ["20g sữa đặc, 100g đá", "25g sữa đặc, 120g đá", "15g sữa đặc, 100g đá", "20g sữa đặc, 120g đá"], answer: "20g sữa đặc, 100g đá" },
    { question: "Nâu phố núi (đá) sử dụng định lượng cafe nào và thông số chiết xuất ra sao?", options: ["18g cafe nâu (nút 2, 33-36s, 30g)", "18g cafe đen (nút 3, 36-40s, 40g)", "13g cafe ý (nút 2, 26-30s, 30g)", "18g cafe nâu (nút 4, 55-65s, 45g)"], answer: "18g cafe nâu (nút 2, 33-36s, 30g)" },
    { question: "Nâu nóng phố núi sử dụng lượng sữa đặc là bao nhiêu?", options: ["15g", "20g", "25g", "30g"], answer: "20g" },
    { question: "Nâu nóng phố núi sử dụng định lượng cafe nào và thông số chiết xuất ra sao?", options: ["18g cafe nâu (nút 4, 55-65s, 45g)", "18g cafe nâu (nút 2, 33-36s, 30g)", "18g cafe đen (nút 4, 55-60s, 45g)", "13g cafe ý (nút 2, 26-30s, 30g)"], answer: "18g cafe nâu (nút 4, 55-65s, 45g)" },
    { question: "Đen phố núi (đá) sử dụng định lượng cafe nào và thông số chiết xuất ra sao?", options: ["18g cafe đen (nút 3, 36-40s, 40g)", "18g cafe đen (nút 4, 55-60s, 45g)", "18g cafe nâu (nút 2, 33-36s, 30g)", "13g cafe ý (nút 2, 26-30s, 30g)"], answer: "18g cafe đen (nút 3, 36-40s, 40g)" },
    { question: "Đen phố núi (đá) sử dụng lượng đá và đường nước là bao nhiêu?", options: ["100g đá, 5ml đường", "120g đá, 10ml đường", "100g đá, 10ml đường", "120g đá, 5ml đường"], answer: "100g đá, 5ml đường" },
    { question: "Đen nóng phố núi sử dụng định lượng cafe nào và thông số chiết xuất ra sao?", options: ["18g cafe đen (nút 4, 55-60s, 45g)", "18g cafe đen (nút 3, 36-40s, 40g)", "18g cafe nâu (nút 4, 55-65s, 45g)", "13g cafe ý (nút 2, 26-30s, 30g)"], answer: "18g cafe đen (nút 4, 55-60s, 45g)" },
    { question: "Đen nóng phố núi được phục vụ kèm với gì?", options: ["1 thanh đường que (cho khách tự bóc)", "5ml đường nước", "10ml đường nước", "Không kèm đường"], answer: "1 thanh đường que (cho khách tự bóc)" },
    { question: "Bạc xỉu đá sử dụng lượng whip, rich, sữa tươi và sữa đặc là bao nhiêu?", options: ["10ml whip, 10ml rich, 30ml sữa tươi, 20ml sữa đặc", "10ml whip, 20ml rich, 20ml sữa tươi, 30ml sữa đặc", "20ml whip, 10ml rich, 30ml sữa tươi, 20ml sữa đặc", "10ml whip, 10ml rich, 40ml sữa tươi, 15ml sữa đặc"], answer: "10ml whip, 10ml rich, 30ml sữa tươi, 20ml sữa đặc" },
    { question: "Bạc xỉu đá sử dụng lượng đá và loại cafe nào?", options: ["120g đá, 18g cafe nâu (nút 2, 33-36s, 30g)", "100g đá, 18g cafe nâu (nút 2, 33-36s, 30g)", "120g đá, 13g cafe ý (nút 2, 26-30s, 30g)", "100g đá, 18g cafe đen (nút 3, 36-40s, 40g)"], answer: "120g đá, 18g cafe nâu (nút 2, 33-36s, 30g)" },
    { question: "Bạc xỉu nóng sử dụng lượng sữa đặc, rich, whip là bao nhiêu?", options: ["20ml sữa đặc, 10ml rich, 10ml whip", "30ml sữa đặc, 10ml rich, 10ml whip", "20ml sữa đặc, 20ml rich, 10ml whip", "20ml sữa đặc, 10ml rich, 20ml whip"], answer: "20ml sữa đặc, 10ml rich, 10ml whip" },
    { question: "Bạc xỉu nóng sử dụng lượng sữa tươi sục nóng là bao nhiêu?", options: ["180ml sữa tươi sục nóng đổ hình", "150ml sữa tươi sục nóng đổ hình", "200ml sữa tươi sục nóng đổ hình", "120ml sữa tươi sục nóng đổ hình"], answer: "180ml sữa tươi sục nóng đổ hình" },
    { question: "Bạc xỉu sữa hạt (đá) sử dụng lượng sữa đặc và sữa hạt là bao nhiêu?", options: ["30ml sữa đặc, 50ml sữa hạt", "20ml sữa đặc, 60ml sữa hạt", "30ml sữa đặc, 60ml sữa hạt", "20ml sữa đặc, 50ml sữa hạt"], answer: "30ml sữa đặc, 50ml sữa hạt" },
    { question: "Bạc xỉu sữa hạt (đá) sử dụng định lượng cafe nào?", options: ["13g cafe ý (nút 2, 26-30s, 30g)", "18g cafe nâu (nút 2, 33-36s, 30g)", "18g cafe đen (nút 3, 36-40s, 40g)", "13g cafe ý (nút 4, 55-65s, 45g)"], answer: "13g cafe ý (nút 2, 26-30s, 30g)" },
    { question: "Bạc xỉu sữa hạt nóng sử dụng lượng sữa hạt sục nóng là bao nhiêu?", options: ["150ml sữa hạt sục nóng", "180ml sữa hạt sục nóng", "120ml sữa hạt sục nóng", "200ml sữa hạt sục nóng"], answer: "150ml sữa hạt sục nóng" },
    { question: "Cà phê muối (chỉ làm đá) sử dụng lượng sữa đặc, cafe muối và kem mặn là bao nhiêu?", options: ["15ml sữa đặc, 40ml cafe muối, 40g kem mặn", "20ml sữa đặc, 40ml cafe muối, 40g kem mặn", "15ml sữa đặc, 30ml cafe muối, 30g kem mặn", "20ml sữa đặc, 30ml cafe muối, 40g kem mặn"], answer: "15ml sữa đặc, 40ml cafe muối, 40g kem mặn" },
    { question: "Americano đá sử dụng lượng nước lọc và đá là bao nhiêu?", options: ["120ml nước lọc, 100g đá", "150ml nước lọc, 100g đá", "120ml nước lọc, 120g đá", "100ml nước lọc, 100g đá"], answer: "120ml nước lọc, 100g đá" },
    { question: "Americano nóng sử dụng lượng nước nóng là bao nhiêu?", options: ["150ml nước nóng", "120ml nước nóng", "180ml nước nóng", "200ml nước nóng"], answer: "150ml nước nóng" },
    { question: "Americano sử dụng loại cafe nào và thông số chiết xuất ra sao?", options: ["18g cafe ý (nút 2, 33-36s, 30g)", "13g cafe ý (nút 2, 26-30s, 30g)", "18g cafe đen (nút 3, 36-40s, 40g)", "18g cafe nâu (nút 2, 33-36s, 30g)"], answer: "18g cafe ý (nút 2, 33-36s, 30g)" },
    { question: "Nâu sài gòn (chỉ làm đá) sử dụng lượng sữa đặc, rich, sữa tươi là bao nhiêu?", options: ["30ml sữa đặc, 20ml rich, 10ml sữa tươi", "20ml sữa đặc, 20ml rich, 10ml sữa tươi", "30ml sữa đặc, 10ml rich, 20ml sữa tươi", "20ml sữa đặc, 30ml rich, 10ml sữa tươi"], answer: "30ml sữa đặc, 20ml rich, 10ml sữa tươi" },
    { question: "Đen sài gòn (chỉ uống đường) sử dụng lượng đường nước là bao nhiêu và cách xử lý thế nào?", options: ["10ml đường (lắc 3 lần rồi đổ ra cốc)", "5ml đường (lắc 3 lần rồi đổ ra cốc)", "10ml đường (quậy đều)", "15ml đường (lắc 3 lần rồi đổ ra cốc)"], answer: "10ml đường (lắc 3 lần rồi đổ ra cốc)" },
    { question: "Capucino nóng sử dụng lượng cafe và sữa sục nóng thế nào?", options: ["13g cafe ý (nút 2, 26-30s, 30g), 200ml sữa sục nóng dùng thìa đổ hình", "18g cafe ý, 180ml sữa sục nóng đổ hình", "13g cafe ý, 200ml sữa sục nóng đổ hình (không dùng thìa)", "18g cafe nâu, 200ml sữa sục nóng dùng thìa đổ hình"], answer: "13g cafe ý (nút 2, 26-30s, 30g), 200ml sữa sục nóng dùng thìa đổ hình" },
    { question: "Latte nóng sử dụng lượng cafe và sữa sục nóng thế nào?", options: ["13g cafe ý (nút 2, 26-30s, 30g), 200ml sữa sục nóng đổ hình", "13g cafe ý, 200ml sữa sục nóng dùng thìa đổ hình", "18g cafe ý, 180ml sữa sục nóng đổ hình", "18g cafe nâu, 200ml sữa sục nóng đổ hình"], answer: "13g cafe ý (nút 2, 26-30s, 30g), 200ml sữa sục nóng đổ hình" },

    // MỤC COLD BREW
    { question: "Tất cả các món Cold Brew (trừ chai đóng sẵn) đều BẮT BUỘC phải làm thao tác gì?", options: ["Chỉ làm đá, ly thủy tinh, đi viền muối cốc", "Chỉ làm đá, ly thủy tinh, đi viền đường cốc", "Chỉ làm nóng, ly sứ", "Làm đá, ly nhựa, viền muối cốc"], answer: "Chỉ làm đá, ly thủy tinh, đi viền muối cốc" },
    { question: "Cold brew dâu tằm sử dụng lượng đường nước và đường hoa quả là bao nhiêu?", options: ["20ml đường, 5ml đường hoa quả", "15ml đường, 5ml đường hoa quả", "20ml đường, 10ml đường hoa quả", "10ml đường, 5ml đường hoa quả"], answer: "20ml đường, 5ml đường hoa quả" },
    { question: "Thao tác pha chế Cold brew dâu tằm là gì?", options: ["Chỉ quậy", "Lắc (Shake)", "Xay", "Sục hơi"], answer: "Chỉ quậy" },
    { question: "Cold brew me đác sử dụng lượng mứt me đác và đường là bao nhiêu?", options: ["30g mứt me đác, 10ml đường, 5ml đhq", "20g mứt me đác, 10ml đường, 5ml đhq", "30g mứt me đác, 15ml đường, 5ml đhq", "40g mứt me đác, 10ml đường, 5ml đhq"], answer: "30g mứt me đác, 10ml đường, 5ml đhq" },
    { question: "Cold brew sấu hà nội sử dụng lượng cốt sấu là bao nhiêu?", options: ["20ml", "30ml", "15ml", "25ml"], answer: "20ml" },
    { question: "Cold brew cam sử dụng lượng cam như thế nào?", options: ["100ml cam (lọc qua dây lọc) quậy đều", "100ml cam (để nguyên tép) quậy đều", "80ml cam (lọc qua dây lọc) lắc đều", "120ml cam (lọc qua dây lọc) quậy đều"], answer: "100ml cam (lọc qua dây lọc) quậy đều" },
    { question: "Thao tác rót của Cold brew cam là gì?", options: ["Rót phân tầng", "Rót trộn lẫn", "Lắc đều rồi rót", "Đổ cam lên trên cùng"], answer: "Rót phân tầng" },
    { question: "Cold brew mơ sử dụng lượng mứt mơ là bao nhiêu?", options: ["30g (gồm 3 quả và nước mơ)", "20g (gồm 2 quả và nước mơ)", "40g (gồm 4 quả và nước mơ)", "30g (chỉ lấy nước mơ)"], answer: "30g (gồm 3 quả và nước mơ)" },
    { question: "Cold brew chanh vàng sử dụng lượng mứt chanh vàng là bao nhiêu?", options: ["10ml", "15ml", "20ml", "5ml"], answer: "10ml" },
    { question: "Cold brew nguyên bản sử dụng lượng cold brew và đá là bao nhiêu?", options: ["100ml cold brew, 100g đá (đầy cốc)", "120ml cold brew, 100g đá", "150ml cold brew, 120g đá", "100ml cold brew, 120g đá (đầy cốc)"], answer: "100ml cold brew, 100g đá (đầy cốc)" },
    { question: "Chai Cold brew bán sẵn chứa bao nhiêu ml?", options: ["250ml", "200ml", "300ml", "330ml"], answer: "250ml" },

    // Mục sen huế
    { question: "Sen huế size M sử dụng lượng nước dừa và nước cốt sen là bao nhiêu?", options: ["150ml nước dừa, 40ml nước cốt sen", "200ml nước dừa, 60ml nước cốt sen", "150ml nước dừa, 50ml nước cốt sen", "120ml nước dừa, 40ml nước cốt sen"], answer: "150ml nước dừa, 40ml nước cốt sen" },
    { question: "Topping của Sen huế size M gồm những gì?", options: ["50g hạt sen, 5g dừa sợi, cánh sen, 4 quả nhãn", "50g hạt sen, 10g dừa sợi, cánh sen, 5 quả nhãn", "40g hạt sen, 5g dừa sợi, 4 quả nhãn", "50g hạt sen, thạch dừa, cánh sen, 4 quả nhãn"], answer: "50g hạt sen, 5g dừa sợi, cánh sen, 4 quả nhãn" },
    { question: "Sen huế size L sử dụng lượng nước dừa và nước cốt sen là bao nhiêu?", options: ["200ml nước dừa, 60ml nước cốt sen", "150ml nước dừa, 40ml nước cốt sen", "250ml nước dừa, 70ml nước cốt sen", "200ml nước dừa, 50ml nước cốt sen"], answer: "200ml nước dừa, 60ml nước cốt sen" },
    { question: "Topping của Sen huế size L gồm những gì?", options: ["50g hạt sen, 5g dừa sợi, cánh sen, 5 quả nhãn", "60g hạt sen, 5g dừa sợi, cánh sen, 4 quả nhãn", "50g hạt sen, 10g dừa sợi, cánh sen, 6 quả nhãn", "50g hạt sen, 5g dừa sợi, cánh sen, 4 quả nhãn"], answer: "50g hạt sen, 5g dừa sợi, cánh sen, 5 quả nhãn" },

    // MỤC Bơ
    { question: "Hỗn hợp để dưới đáy cốc của món Bơ dừa non gồm những gì?", options: ["35ml cốt dừa, 15ml đường, 10ml whiping, đá vụn 20g (5 viên)", "30ml cốt dừa, 10ml đường, 15ml whiping, đá vụn 20g", "40ml cốt dừa, 15ml đường, 10ml whiping, đá vụn 30g", "35ml cốt dừa, 20ml đường, 10ml whiping, đá vụn 20g"], answer: "35ml cốt dừa, 15ml đường, 10ml whiping, đá vụn 20g (5 viên)" },
    { question: "Nguyên liệu cho vào cối xay của Bơ dừa non là gì?", options: ["1 túi bơ, 50ml nước lọc, 30ml sữa tươi, 20g sữa đặc, 10ml siro lá nếp", "1 túi bơ, 30ml nước lọc, 50ml sữa tươi, 20g sữa đặc, 10ml siro lá nếp", "1 túi bơ, 50ml nước lọc, 30ml sữa tươi, 30g sữa đặc, 5ml siro lá nếp", "1 túi bơ, 50ml nước lọc, 40ml sữa tươi, 20g sữa đặc, 10ml siro lá nếp"], answer: "1 túi bơ, 50ml nước lọc, 30ml sữa tươi, 20g sữa đặc, 10ml siro lá nếp" },
    { question: "Nguyên liệu cho vào cối xay của món Kem bơ là gì?", options: ["1 túi bơ, 30g đá viên (5 viên), 50ml nước lọc, 30ml sữa tươi, 30ml cốt dừa, 15ml đường, 20ml sữa đặc, 10ml siro lá nếp", "1 túi bơ, 50g đá viên, 50ml nước lọc, 30ml sữa tươi, 30ml cốt dừa, 20ml sữa đặc, 10ml siro lá nếp", "1 túi bơ, 30g đá viên, 30ml nước lọc, 50ml sữa tươi, 20ml cốt dừa, 20ml sữa đặc, 10ml siro lá nếp", "1 túi bơ, 30g đá viên, 50ml nước lọc, 30ml sữa tươi, 30ml cốt dừa, 30ml sữa đặc, 10ml siro lá nếp"], answer: "1 túi bơ, 30g đá viên (5 viên), 50ml nước lọc, 30ml sữa tươi, 30ml cốt dừa, 15ml đường, 20ml sữa đặc, 10ml siro lá nếp" },
    { question: "Topping của món Kem bơ là gì?", options: ["80g kem dừa (1 viên), dừa khô 5g", "100g kem dừa (2 viên), dừa khô 5g", "50g kem dừa (1 viên), vụn điều 3g", "80g kem dừa (1 viên), vụn điều 5g"], answer: "80g kem dừa (1 viên), dừa khô 5g" },
    { question: "Nguyên liệu xay của Sinh tố bơ giống món nào nhưng thay đổi topping?", options: ["Kem bơ, decor vụn điều 3g", "Bơ dừa non, decor dừa khô 5g", "Kem bơ, decor dừa khô 5g", "Bơ dừa non, decor vụn điều 3g"], answer: "Kem bơ, decor vụn điều 3g" },

    // Mục Trà Trái Cây
    { question: "Lục trà xoài sử dụng lượng nền lục trà và nước lọc là bao nhiêu?", options: ["100ml lục trà, 50ml nước lọc", "120ml lục trà, 30ml nước lọc", "150ml lục trà, không nước lọc", "80ml lục trà, 50ml nước lọc"], answer: "100ml lục trà, 50ml nước lọc" },
    { question: "Lục trà xoài sử dụng lượng mứt xoài là bao nhiêu?", options: ["30ml", "20ml", "40ml", "50ml"], answer: "30ml" },
    { question: "Trà đào sấu sử dụng lượng nước cốt sấu và mứt đào là bao nhiêu?", options: ["30ml nước cốt sấu, 20g mứt đào", "20ml nước cốt sấu, 30g mứt đào", "30ml nước cốt sấu, 30g mứt đào", "40ml nước cốt sấu, 20g mứt đào"], answer: "30ml nước cốt sấu, 20g mứt đào" },
    { question: "Trong Trà đào sấu, Atiso được xử lý như thế nào?", options: ["30ml atiso rót lên trên", "Lắc chung với trà", "Trộn chung dưới đáy cốc", "Không sử dụng Atiso"], answer: "30ml atiso rót lên trên" },
    { question: "Lục trà me đác sử dụng lượng mứt me đác là bao nhiêu?", options: ["30ml", "20ml", "40ml", "50ml"], answer: "30ml" },
    { question: "Lục trà me đác sử dụng loại thạch gì và lượng bao nhiêu?", options: ["70g thạch hồng đào", "50g thạch dừa", "70g thạch atiso", "70g thạch trà"], answer: "70g thạch hồng đào" },
    { question: "Mơ trà sử dụng lượng mơ là bao nhiêu?", options: ["30g mơ (3 quả + nước mơ)", "20g (2 quả)", "40g (4 quả)", "50g (5 quả)"], answer: "30g mơ (3 quả + nước mơ)" },
    { question: "Mơ trà sử dụng cốt atiso như thế nào?", options: ["30ml cốt atiso rót lên trên", "Khuấy đều cùng trà", "Không sử dụng Atiso", "20ml cốt atiso rót dưới đáy"], answer: "30ml cốt atiso rót lên trên" },
    { question: "Trà đào cam sả sử dụng lượng hồng trà và nước sôi là bao nhiêu?", options: ["20ml hồng trà, 80ml nước sôi", "30ml hồng trà, 70ml nước sôi", "20ml hồng trà, 100ml nước sôi", "50ml hồng trà, 50ml nước sôi"], answer: "20ml hồng trà, 80ml nước sôi" },
    { question: "Trà đào cam sả sử dụng lượng cốt sả và mứt đào là bao nhiêu?", options: ["30ml cốt sả, 20g mứt đào", "20ml cốt sả, 30g mứt đào", "30ml cốt sả, 30g mứt đào", "40ml cốt sả, 25g mứt đào"], answer: "30ml cốt sả, 20g mứt đào" },
    { question: "Xoài lài chanh leo sử dụng lượng mứt xoài và chanh leo tươi là bao nhiêu?", options: ["20g mứt xoài, 1 túi chanh leo hạt", "30g mứt xoài, 1 túi chanh leo hạt", "20g mứt xoài, nửa túi chanh leo hạt", "30g mứt xoài, nửa túi chanh leo hạt"], answer: "20g mứt xoài, 1 túi chanh leo hạt" },
    { question: "Xoài lài chanh leo sử dụng loại thạch gì?", options: ["70 thạch hồng đào", "70g thạch trà", "50g thạch dừa", "50g pudding xoài"], answer: "70 thạch hồng đào" },

    // Mục Trà Sữa
    { question: "Lục trà sữa sử dụng lượng lục trà và sữa tươi là bao nhiêu?", options: ["150ml lục trà, 50ml sữa tươi", "120ml lục trà, 60ml sữa tươi", "180ml lục trà, 30ml sữa tươi", "150ml lục trà, 30ml sữa tươi"], answer: "150ml lục trà, 50ml sữa tươi" },
    { question: "Lục trà sữa sử dụng lượng sữa nước, sữa đặc là bao nhiêu?", options: ["30ml sữa nước, 30ml sữa đặc", "20ml sữa nước, 30ml sữa đặc", "30ml sữa nước, 20ml sữa đặc", "30ml sữa nước, 40ml sữa đặc"], answer: "30ml sữa nước, 30ml sữa đặc" },
    { question: "Lục xoài sữa sử dụng lượng mứt xoài là bao nhiêu?", options: ["30g", "20g", "40g", "50g"], answer: "30g" },
    { question: "Topping của Lục xoài sữa gồm những gì?", options: ["Puding xoài 50g, 50g thạch dừa", "Puding xoài 70g", "Thạch hồng đào 50g, thạch dừa 50g", "Puding xoài 50g, thạch atiso 50g"], answer: "Puding xoài 50g, 50g thạch dừa" },
    { question: "Trà sữa đào hồng sử dụng lượng hồng trà là bao nhiêu?", options: ["70ml", "100ml", "120ml", "150ml"], answer: "70ml" },
    { question: "Trà sữa đào hồng sử dụng lượng mứt đào hồng là bao nhiêu?", options: ["20g", "15g", "25g", "30g"], answer: "20g" },
    { question: "Hồng trà hạt dẻ sử dụng lượng hồng trà là bao nhiêu?", options: ["70ml", "100ml", "120ml", "150ml"], answer: "70ml" },
    { question: "Topping của Hồng trà hạt dẻ gồm những gì?", options: ["50g thạch dừa, 40g kem hạt dẻ", "40g kem hạt dẻ, thạch hồng đào", "Chỉ có 40g kem hạt dẻ", "50g kem hạt dẻ, 50g thạch dừa"], answer: "50g thạch dừa, 40g kem hạt dẻ" },
    { question: "Trà sữa gạo sử dụng lượng trà sữa gạo là bao nhiêu?", options: ["250ml", "200ml", "300ml", "350ml"], answer: "250ml" },
    { question: "Trà sữa gạo hạt dẻ sử dụng lượng trà sữa gạo là bao nhiêu?", options: ["200ml", "250ml", "150ml", "300ml"], answer: "200ml" },
    { question: "Trà sữa gạo pudding phomai sử dụng lượng thạch phô mai là bao nhiêu?", options: ["70g", "50g", "60g", "80g"], answer: "70g" },

    // Mục nước trái cây
    { question: "Nước dâu tằm sử dụng bao nhiêu tép dâu tằm?", options: ["2 tép dâu tằm (60ml)", "1 tép dâu tằm (30ml)", "3 tép dâu tằm (90ml)", "4 tép dâu tằm (120ml)"], answer: "2 tép dâu tằm (60ml)" },
    { question: "Nước dâu tằm được mix thêm mứt gì?", options: ["10g mứt đào", "20g mứt đào", "10g mứt xoài", "Không mix thêm mứt"], answer: "10g mứt đào" },
    { question: "Nước dưa hấu cần dùng bao nhiêu gram dưa hấu quả để ép?", options: ["400g", "300g", "500g", "600g"], answer: "400g" },
    { question: "Nước cam tươi cần dùng bao nhiêu gram cam quả để vắt?", options: ["500g", "400g", "300g", "600g"], answer: "500g" },
    { question: "Nước cam tươi sử dụng lượng đường là bao nhiêu?", options: ["15ml (có thể tăng do cam chua)", "10ml", "20ml", "25ml"], answer: "15ml (có thể tăng do cam chua)" },
    { question: "Chanh leo xoài sử dụng lượng chanh leo và mứt xoài là bao nhiêu?", options: ["1 túi chanh leo (30ml), 30ml mứt xoài", "1 túi chanh leo, 20ml mứt xoài", "2 túi chanh leo, 30ml mứt xoài", "1 túi chanh leo, 40ml mứt xoài"], answer: "1 túi chanh leo (30ml), 30ml mứt xoài" },
    { question: "Chanh vàng violet (đá) sử dụng lượng đường là bao nhiêu?", options: ["40ml", "30ml", "20ml", "50ml"], answer: "40ml" },
    { question: "Chanh vàng violet (đá) rót thành phần gì lên trên cùng?", options: ["30ml cốt hoa đậu biếc", "30ml cốt atiso", "20ml siro violet", "10ml siro hoa hồng"], answer: "30ml cốt hoa đậu biếc" },
    { question: "Chanh vàng (nóng) sử dụng lượng nước sôi là bao nhiêu?", options: ["150ml", "100ml", "120ml", "200ml"], answer: "150ml" },

    // Mục đồ nóng
    { question: "Sữa gừng táo đỏ sử dụng lượng sữa tươi là bao nhiêu?", options: ["200ml", "150ml", "180ml", "250ml"], answer: "200ml" },
    { question: "Sữa gừng táo đỏ sử dụng loại sốt nào và định lượng bao nhiêu?", options: ["10ml sốt nướng, 10ml sốt táo đỏ", "20ml sốt táo đỏ", "15ml sốt nướng, 5ml sốt táo đỏ", "10ml sốt caramel, 10ml sốt táo đỏ"], answer: "10ml sốt nướng, 10ml sốt táo đỏ" },
    { question: "Decor của Sữa gừng táo đỏ gồm những gì?", options: ["2g hoa hồng, 2 lát gừng, 2 quả táo đỏ", "1g hoa hồng, 1 lát gừng, 3 quả táo đỏ", "Bột quế, 2 lát gừng", "3 lát gừng, 2 quả táo đỏ"], answer: "2g hoa hồng, 2 lát gừng, 2 quả táo đỏ" },
    { question: "Lài sữa hạt dẻ nóng sử dụng nền trà gì và lượng bao nhiêu?", options: ["150ml lục trà", "150ml hồng trà", "150ml sữa tươi", "120ml lục trà"], answer: "150ml lục trà" },
    { question: "Lài sữa hạt dẻ nóng sử dụng lượng bột hạt dẻ là bao nhiêu?", options: ["20g bột hạt dẻ", "10g", "15g", "25g"], answer: "20g bột hạt dẻ" },

    // Mục khác
    { question: "Matcha sữa hạt sử dụng lượng sữa hạt là bao nhiêu?", options: ["50ml", "30ml", "40ml", "60ml"], answer: "50ml" },
    { question: "Matcha sữa hạt sử dụng lượng bột matcha là bao nhiêu?", options: ["1 túi matcha (3g)", "2g", "5g", "10g"], answer: "1 túi matcha (3g)" },
    { question: "Coco matcha sử dụng loại topping gì và lượng bao nhiêu?", options: ["100g kem dừa, 5g dừa khô", "50g kem dừa, vụn điều", "80g kem dừa, dừa khô", "120g kem dừa, dừa sấy"], answer: "100g kem dừa, 5g dừa khô" },
    { question: "Kem dừa (phục vụ ra cốc riêng) có khối lượng là bao nhiêu?", options: ["250g kem dừa", "150g", "200g", "300g"], answer: "250g kem dừa" },
    { question: "Sữa chua cafe sử dụng lượng cà phê muối là bao nhiêu?", options: ["20ml cà phê muối", "10ml", "30ml", "40ml"], answer: "20ml cà phê muối" },
    { question: "Sữa chua hoa quả và sữa chua dẻo hoa quả sử dụng bao nhiêu gram hoa quả các loại?", options: ["200g", "150g", "250g", "100g"], answer: "200g" },
    { question: "Sữa chua dẻo hoa quả sử dụng bao nhiêu gram sữa chua dẻo?", options: ["100g", "50g", "80g", "120g"], answer: "100g" },

    // Các loại kem và trà
    { question: "Công thức làm Kem Mặn chuẩn sử dụng tỷ lệ Whipping Anchor và Base là bao nhiêu?", options: ["400g Whipping anchor, 600g base", "300g Whip, 500g Base", "500g Whip, 500g Base", "400g Whip, 500g Base"], answer: "400g Whipping anchor, 600g base" },
    { question: "Làm Kem Mặn sử dụng lượng đường nước và muối hồng là bao nhiêu?", options: ["60ml đường nước, 7g muối hồng", "50ml đường nước, 5g muối", "60ml đường nước, 10g muối", "80ml đường nước, 7g muối"], answer: "60ml đường nước, 7g muối hồng" },
    { question: "Công thức làm kem hạt dẻ cười sử dụng tỷ lệ sữa tươi, base, whipping là bao nhiêu?", options: ["100ml sữa tươi, 100ml base, 100ml whipping", "150ml sữa tươi, 100ml base, 100ml whipping", "100ml sữa tươi, 150ml base, 100ml whipping", "100ml sữa tươi, 100ml base, 150ml whipping"], answer: "100ml sữa tươi, 100ml base, 100ml whipping" },
    { question: "Công thức làm kem hạt dẻ cười sử dụng lượng bột hạt dẻ cười là bao nhiêu?", options: ["100g", "50g", "80g", "150g"], answer: "100g" },
    { question: "Để làm thạch hồng đào, 1 túi Atiso cần ủ với bao nhiêu lít nước sôi và thời gian bao lâu?", options: ["2000ml nước sôi ủ 10 phút", "1500ml nước sôi ủ 10 phút", "2500ml nước sôi ủ 12 phút", "3000ml nước sôi ủ 15 phút"], answer: "2000ml nước sôi ủ 10 phút" },
    { question: "Quy trình ủ Hồng trà sử dụng lượng nước và thời gian như thế nào?", options: ["1300ml nước sôi ủ 12 phút vớt (thu 700ml)", "1500ml nước sôi ủ 15 phút vớt", "1000ml nước sôi ủ 10 phút vớt", "2000ml nước sôi ủ 12 phút vớt"], answer: "1300ml nước sôi ủ 12 phút vớt (thu 700ml)" },
    { question: "Quy trình ủ Trà Sữa Gạo sử dụng 1 túi trà gạo ủ với bao nhiêu ml nước sôi và thời gian bao lâu?", options: ["2500ml nước sôi ủ 18 phút", "2000ml nước sôi ủ 15 phút", "3000ml nước sôi ủ 20 phút", "3500ml nước sôi ủ 18 phút"], answer: "2500ml nước sôi ủ 18 phút" },
    { question: "Thao tác vớt bã trà của Trà Sữa Gạo là gì?", options: ["Dầm mạnh 10 lần rồi vớt bã trà", "Vớt nhẹ không tác động", "Vắt kiệt bã trà", "Lọc qua rây"], answer: "Dầm mạnh 10 lần rồi vớt bã trà" },
    { question: "Trà sữa gạo (sau khi mix bột sữa, sốt nướng, đường, đá) có tổng lượng thành phẩm là bao nhiêu?", options: ["4000ml", "3000ml", "3500ml", "4500ml"], answer: "4000ml" },
    { question: "Quy trình ủ Lục Trà chuẩn là gì?", options: ["1 tép lục trà (100g) + 2000ml nước sôi, ủ 12p vớt nhẹ (không tác động)", "1 tép lục trà + 1500ml nước sôi, ủ 10p", "1 tép lục trà + 2500ml nước sôi, ủ 15p dầm mạnh", "1 tép lục trà + 2000ml nước sôi, ủ 12p dầm mạnh"], answer: "1 tép lục trà (100g) + 2000ml nước sôi, ủ 12p vớt nhẹ (không tác động)" },
    { question: "Cách làm cốt sả chuẩn tỷ lệ và thời gian xay là bao nhiêu?", options: ["200g sả + 600ml nước sôi xay 10s rồi lọc", "100g sả + 500ml nước sôi xay 10s", "200g sả + 500ml nước sôi xay 20s", "300g sả + 600ml nước sôi xay 15s"], answer: "200g sả + 600ml nước sôi xay 10s rồi lọc" },
    { question: "Công thức ủ Atiso (làm cốt Atiso) là gì?", options: ["1 túi atiso + 400ml nước sôi ủ 10p rồi sock đá 600g tổng 1000ml", "1 túi atiso + 500ml nước sôi ủ 12p sock đá 500g", "1 túi atiso + 1000ml nước sôi ủ 10p", "1 túi atiso + 600ml nước sôi ủ 15p sock đá 400g"], answer: "1 túi atiso + 400ml nước sôi ủ 10p rồi sock đá 600g tổng 1000ml" }
];
